apiVersion: skaffold/v2beta29
kind: Config

metadata:
  name: popular-slides

build:
  artifacts:
    - image: bigdata/spotify-web-app
      context: web-app

    - image: bigdata/spark-app
      context: spark-app

deploy:
  kubectl:
    manifests:
      - k8s/*.yaml
