apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: spotify-track-data
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 62400
